version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bdeng_postgres
    restart: always
    environment:
      POSTGRES_USER: bdeng
      POSTGRES_PASSWORD: bdengpass
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: